"""init

Revision ID: 0f4e7c4ad08a
Revises: 
Create Date: 2024-06-30 14:54:49.870322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4e7c4ad08a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('request')
    )
    op.create_table('vacancy',
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('typeofemployment', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('viewers_count', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request'], ['request.request'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
