"""init3

Revision ID: 1815d5d15185
Revises: 7091468b7a34
Create Date: 2024-06-30 15:10:44.713579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1815d5d15185'
down_revision: Union[str, None] = '7091468b7a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy')
    op.drop_table('request')
    # ### end Alembic commands ###
