"""final4

Revision ID: 2dc64f27bdf9
Revises: 0a33ea93cb54
Create Date: 2024-07-04 13:26:11.119571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc64f27bdf9'
down_revision: Union[str, None] = '0a33ea93cb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy')
    op.drop_table('request')
    # ### end Alembic commands ###
