"""empty message

Revision ID: 6af0e15bb992
Revises: 132d81800bbd
Create Date: 2024-07-04 17:50:17.557443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af0e15bb992'
down_revision: Union[str, None] = '132d81800bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('request')
    )
    op.create_table('vacancy',
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('typeofemployment', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('viewers_count', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request'], ['request.request'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy')
    op.drop_table('request')
    # ### end Alembic commands ###
