"""init2

Revision ID: 7091468b7a34
Revises: 0f4e7c4ad08a
Create Date: 2024-06-30 14:58:56.714721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7091468b7a34'
down_revision: Union[str, None] = '0f4e7c4ad08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy')
    op.drop_table('request')
    # ### end Alembic commands ###
