"""final2

Revision ID: df3c6a785d9f
Revises: dc726173bf17
Create Date: 2024-07-04 02:32:31.949924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df3c6a785d9f'
down_revision: Union[str, None] = 'dc726173bf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy')
    op.drop_table('request')
    # ### end Alembic commands ###
